name: Delete tag and release - jcs
description: An action to delete a tag, and optionally its associated release.
author: "Shen, Jen-Chieh"

branding:
  color: "red"
  icon: "delete"

inputs:
  tag_name:
    description: tag name
    required: true
  delete_release:
    description: whether to delete release or not
    required: false
    default: true
  repo:
    description: target repository as <owner>/<repository>
    required: false

runs:
  using: "node20"
  main: "index.js"
